name: Lint(Web)
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: web
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: Install dependencies
              run: |
                  pnpm install
            - name: Run lint
              run: pnpm run lint:lint-staged
