name: Lint(Web)
on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    lint:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "web"
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
                  cache-dependency-path: "**/pnpm-lock.yaml"
            - name: Install dependencies
              run: |
                  pnpm install
            - name: Run lint
              run: pnpm run lint
            - name: Commit files
              id: commit
              continue-on-error: true
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git commit -a -m "style: lint"
            - name: Push changes
              uses: ad-m/github-push-action@master
              if: ${{ steps.commit.outcome == 'success' }}
              with:
                  branch: ${{ github.head_ref }}
                  directory: "web"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
